site_name: Cakebox

site_description: Documentation for the Cakebox project.

dev_addr: 0.0.0.0:8000

docs_dir: docs/sources

include_search: true

theme: readthedocs

pages:

# Home:
- ['index.md', 'Home']

# Quickstart:
- ['quickstart.md', '', 'Quickstart']

# Features:
- ['features.md', '', 'Features']

# Usage:
- ['usage/hosts-file.md', 'Usage', 'Hosts File']
- ['usage/cakebox-commands.md', 'Usage', 'Cakebox Commands']
- ['usage/cakebox-yaml.md', 'Usage', 'Cakebox.yaml']
- ['usage/backups.md', 'Usage', 'Backups']
- ['usage/logs.md', 'Usage', 'Logs']

# Tutorials:
- ['tutorials/creating-your-first-website.md', 'Tutorials', 'Creating Your First Website']
- ['tutorials/connecting-to-your-box.md', 'Tutorials', 'Connecting To Your Box']
- ['tutorials/connecting-to-your-databases.md', 'Tutorials', 'Connecting To Your Databases']
- ['tutorials/updating-your-box.md', 'Tutorials', 'Updating Your Box']
- ['tutorials/hardening-box-authentication.md', 'Tutorials', 'Hardening Box Authentication']
- ['tutorials/connecting-your-github-ssh-key.md', 'Tutorials', 'Connecting Your Github SSH Key']

# Additional Information:
- ['additional/credentials.md', 'Additional Information', 'Credentials']
- ['additional/known-limitations.md', 'Additional Information', 'Known Limitations']
- ['additional/contributing.md', 'Additional Information', 'Contributing']
